# Generated by Django 4.0.6 on 2022-07-28 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('songlist', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='inuisong',
            table='list',
        ),
    ]
