# Generated by Django 4.0.6 on 2022-07-28 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songlist', '0002_alter_inuisong_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inuisong',
            name='upload_date',
            field=models.DateField(null=True),
        ),
    ]
